spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show-sql: false
    defer-datasource-initialization: true

---
# 'local' profile
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create

---
# 'perform' profile
spring:
  config:
    activate:
      on-profile: perform
  jpa:
    hibernate:
      ddl-auto: create # mysql 세팅 후 none 으로 변경해야함
