oauth:
  kakao:
    redirect_uri: http://localhost:8080/api/oauth/callback
    login_page_url: "https://kauth.kakao.com/oauth/authorize?client_id=%s&redirect_uri=%s&response_type=%s"
    grant_type: authorization_code
    client_id: 5828792c370aa10f250601d6c669d953
    response_type: code
    service:
      token_url: https://kauth.kakao.com/
      api_url: https://kapi.kakao.com/


secret:
  secretKey: sample-secretKey-sample-secretKey
  accessTokenExpiredMillisecond: 1800000
  refreshTokenExpiredMillisecond: 604800000

feign:
  client:
    config:
      default:
        loggerLevel: FULL