version: "3.8"

services:

  # JVM Metric monitoring server
  monitoring-server:
    image: sikdorak/monitoring-server
    container_name: monitoring-server
    build:
      context: ./monitoring-server
    ports:
      - "9090:9090"
    networks:
      - sbn-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090" ]
      interval: 5s
      timeout: 5s
      retries: 6

  # 식도락 API 서버 : 부하테스트 대상
  sikdorak-was:
    image: sikdorak/was
    # ngrinder 에서 이 컨테이너를 찾을 수 있도록 이름을 url 형식으로 지음
    container_name: api.sikdorak-was.net
    build:
      context: ./sikdorak
    ports:
      - "8080:8080"
    networks:
      - sbn-net
    # ngrinder monitor 설치를 위해 controller 실행 후 실행
    depends_on:
      monitoring-server:
        condition: service_healthy
      controller:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 512M

  # 식도락 DB 서버
  sikdorak-db:
    image: mysql:8.0
    container_name: sikdorak-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - type: volume
        source: sikdorak-data
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/conf.d
        target: /etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - sbn-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 512M

  # ngrinder controller : agent 를 통해 부하 테스트 수행
  # 공식 이미지가 로컬에서 실행이 잘 되지않아, 직접 컨테이너 실행
  # 공식 이미지 : https://hub.docker.com/r/ngrinder/controller
  controller:
    image: sikdorak/ngrinder-controller
    container_name: controller
    build:
      context: ./docker/ngrinder-controller
    volumes:
      - type: volume
        source: controller-data
        target: /app/controller-home
    ports:
      - "80:80"
    networks:
      - sbn-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 4

  # ngrinder agent : 부하 테스트 요청을 보내는 주체
  agent:
    image: ngrinder/agent:3.5.8
    networks:
      - sbn-net
    depends_on:
      controller:
        condition: service_healthy

networks:
  sbn-net:
    name: sbn-net
    driver: bridge

volumes:
  sikdorak-data:
    name: sikdorak-data
  controller-data:
    name: controller-data
