spring:
  jpa:
    database: mysql
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate.show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testDB
    url: jdbc:mysql://localhost:3306/testDB?rewriteBatchedStatements=true
    username: root
    password: 1234
