spring:
  profiles:
    active: local
  config:
    import:
      - config/api-config.yml
      - config/aws-credential.yml
      - config/aws-s3.yml
      - config/jpa-config.yml
      - config/monitoring-config.yml
      - config/oauth-config.yml
      - config/web-config.yml