spring:
  # mysql 로 변경해야함
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sikdorakDB;NON_KEYWORDS=USER
    username: sa
    password:

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    com.jjikmuk.sikdorak: info
    org.hibernate.SQL: info
